import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useSession, signIn, signOut } from "next-auth/react";
import { useEffect, useState } from "react";

export default function Home() {
  const { data: session, status } = useSession();
  const [products, setProducts] = useState([]);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState(null);

  useEffect(() => {
    if (session) {
      setIsLoading(true);
      fetch("https://fakestoreapi.com/products")
        .then((res) => res.json())
        .then((data) => {
          setIsLoading(false);
          setProducts(data);
        })
        .catch((error) => {
          setIsLoading(false);
          setError(error);
        });
    }
  }, [session]);

  const handleSignIn = (provider) => {
    signIn(provider);
  };

  const handleSignOut = (provider) => {
    signOut(provider);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Shopping</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {status === "loading" && <div>Loading...</div>}
      {error && <div>Error: {error.message}</div>}
      {session && (
        <main className={styles.main}>
          <div className={styles.header}>
            <h4 className={styles.headertext}>
              Welcome {session.user.name} <br /> Enjoy Shopping
            </h4>
            <button
              className={styles.signInButton}
              onClick={() => handleSignOut("google")}
            >
              Sign out
            </button>
          </div>
          {isLoading ? (
            <div>Loading...</div>
          ) : (
            <div>
              <h1 className={styles.title}>My Products</h1>
              <div className={styles.productList}>
                {products.map((product) => (
                  <div className={styles.productCard} key={product.id}>
                    <Image
                      src={product.image}
                      alt={product.title}
                      width={300}
                      height={200}
                    />
                    <div className={styles.productCardContent}>
                      <h2>{product.title}</h2>
                      <p>{product.description}</p>
                      <p className={styles.price}>${product.price}</p>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}
        </main>
      )}
      {!session && (
        <div className={styles.signInContainer}>
          <button
            className={styles.signInButton}
            onClick={() => handleSignIn("google")}
          >
            Sign in with Google
          </button>
        </div>
      )}
    </div>
  );
}
